name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Configure Gradle
        run: |
          echo "org.gradle.jvmargs=-Xmx2g -XX:MaxPermSize=512m" >> gradle.properties

      - name: Disable Gradle Daemon
        run: echo "org.gradle.daemon=false" >> gradle.properties

      - name: Debug System Resources
        run: |
          free -h
          df -h
          ulimit -a

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/debug/*.apk
